version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: git reset --hard HEAD && git pull origin
      - run: npm install
      - run: npm run angular-blank
      - run: npm run angular-sidemenu
      - run: npm run angular-tabs
      - run: npm run angular-conf
      - run: npm run output
      - run: git config user.email "${GITHUB_EMAIL}"
      - run: git config user.name "${GITHUB_USERNAME}"
      - run: git add ./
      - run: git commit -m 'record(lighthouse):daily cron'
      - run: git push origin master
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  normal_workflow:
    jobs:
    - build
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 10,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
